---

sudo: true

language: ruby
cached: bundler

before_install:
  - sudo apt-get install -y awscli
  - git clone https://github.com/nuex/zodiac.git /tmp/zodiac
  - cd /tmp/zodiac && sudo make install
  - rm -fr /tmp/zodiac

install: bundle install

script: make
