baseurl = "https://www.deployawebsite.com/"
title = "Deploy a Web Site"
languageCode = "en-us"
theme = "blackieops-deploy"

[params]
	author = "Alex Blackie"

[[menu.main]]
	name = "Introduction"
	url = "/"
	weight = 0

[[menu.main]]
	name = "Static Sites"
	url = "/static-sites"
	weight = 0

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
